// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "github.com/daniel5u/suisei/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields:
func (_m *Repository) Fetch() ([]user.Domain, error) {
	ret := _m.Called()

	var r0 []user.Domain
	if rf, ok := ret.Get(0).(func() []user.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id int) (user.Domain, error) {
	ret := _m.Called(id)

	var r0 user.Domain
	if rf, ok := ret.Get(0).(func(int) user.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: userDomain
func (_m *Repository) Store(userDomain user.Domain) (user.Domain, error) {
	ret := _m.Called(userDomain)

	var r0 user.Domain
	if rf, ok := ret.Get(0).(func(user.Domain) user.Domain); ok {
		r0 = rf(userDomain)
	} else {
		r0 = ret.Get(0).(user.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.Domain) error); ok {
		r1 = rf(userDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userDomain, id
func (_m *Repository) Update(userDomain user.Domain, id int) (user.Domain, error) {
	ret := _m.Called(userDomain, id)

	var r0 user.Domain
	if rf, ok := ret.Get(0).(func(user.Domain, int) user.Domain); ok {
		r0 = rf(userDomain, id)
	} else {
		r0 = ret.Get(0).(user.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.Domain, int) error); ok {
		r1 = rf(userDomain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: userDomain, id
func (_m *Repository) UpdateBalance(userDomain user.Domain, id int) error {
	ret := _m.Called(userDomain, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.Domain, int) error); ok {
		r0 = rf(userDomain, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
