// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	booktransaction "github.com/daniel5u/suisei/domain/booktransaction"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteByTransactionID provides a mock function with given fields: transactionid
func (_m *Repository) DeleteByTransactionID(transactionid int) error {
	ret := _m.Called(transactionid)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(transactionid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: booktransactionDomain
func (_m *Repository) Store(booktransactionDomain booktransaction.Domain) (booktransaction.Domain, error) {
	ret := _m.Called(booktransactionDomain)

	var r0 booktransaction.Domain
	if rf, ok := ret.Get(0).(func(booktransaction.Domain) booktransaction.Domain); ok {
		r0 = rf(booktransactionDomain)
	} else {
		r0 = ret.Get(0).(booktransaction.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(booktransaction.Domain) error); ok {
		r1 = rf(booktransactionDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
